### ISSUE TITLE
disjointExons removed in Bioconductor 3.17

### ISSUE THREAD

**Issue by yeyuan98** [jianhong/ChIPpeakAnno#21]
Hi Jianhong,

Thanks so much for your great package. I noticed that in the bioconductor development version 3.17, `disjointExons` method is removed from ensembldb and GenomicFeatures packages, causing your ChIPpeakAnno package to fail during build.

Would it be possible to fix this issue simply by changing your code like the following?

from `R/privateUtil.R, line 616-618`

```
disjointExons(ranges,
                                      aggregateGenes=FALSE,
                                      includeTranscripts=TRUE)
```

to

```
GenomicFeatures::exonicParts(ranges,
                                      linked.to.single.gene.only=TRUE)
```

Commits related to the removal of `disjointExons`:
[ensembldb](https://github.com/jorainer/ensembldb/commit/4bd6ababfc909e979dcb6f7cb5f8cc9a9ddde1ea)
[GenomicFeatures](https://github.com/Bioconductor/GenomicFeatures/commit/df02299383965c99c5abf592596ccc22c08a9bfa)

Thanks a lot for your time!

**Comment by jianhong** [comment]
Hi Ye Yuan,

Thank you for reporting. I just pushed the patch. It will take several days for updating.

Jianhong.

From: Ye Yuan ***@***.***>
Date: Saturday, November 12, 2022 at 12:47 PM
To: jianhong/ChIPpeakAnno ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jianhong/ChIPpeakAnno] disjointExons removed in Bioconductor 3.17 (Issue #21)

Hi Jianhong,

Thanks so much for your great package. I noticed that in the bioconductor development version 3.17, disjointExons method is removed from ensembldb and GenomicFeatures packages, causing your ChIPpeakAnno package to fail during build.

Would it be possible to fix this issue simply by changing your code like the following?

from R/privateUtil.R, line 616-618

disjointExons(ranges,

                                      aggregateGenes=FALSE,

                                      includeTranscripts=TRUE)

to

GenomicFeatures::exonicParts(ranges,

                                      linked.to.single.gene.only=TRUE)

Commits related to the removal of disjointExons:
ensembldb<https://github.com/jorainer/ensembldb/commit/4bd6ababfc909e979dcb6f7cb5f8cc9a9ddde1ea>
GenomicFeatures<https://github.com/Bioconductor/GenomicFeatures/commit/df02299383965c99c5abf592596ccc22c08a9bfa>

Thanks a lot for your time!
