### ISSUE TITLE
How to set the circle size same proportion of the number of peaks when there are more than 2 sets using `makeVennDiagram`?

### ISSUE THREAD

**Issue by danli349** [jianhong/ChIPpeakAnno#26]
Hello,

```
library(ChIPpeakAnno)

Control_Menin <- toGRanges("peaks/changeformat/4934_Control_Menin_peaks.narrowPeak",
                               format="narrowPeak", header=FALSE)
Control_Menin$score <- as.numeric(Control_Menin$score)
Control_Menin_reduce <- reduce(Control_Menin, drop.empty.ranges=FALSE, min.gapwidth=1L,
                      with.revmap=FALSE,
                      with.inframe.attrib=FALSE, ignore.strand=FALSE)


Control_Set1a <- toGRanges("peaks/changeformat/4934_Control_Set1a_peaks.narrowPeak",
                           format="narrowPeak", header=FALSE)
Control_Set1a$score <- as.numeric(Control_Set1a$score)
Control_Set1a_reduce <- reduce(Control_Set1a, drop.empty.ranges=FALSE, min.gapwidth=1L,
                               with.revmap=FALSE,
                               with.inframe.attrib=FALSE, ignore.strand=FALSE)

MLL4_MERGED <- toGRanges("peaks/changeformat/SICER_HOMER_MLL4_MERGED.bed",
                             format="BED", header=FALSE)
MLL4_MERGED$score <- as.numeric(MLL4_MERGED$score)
MLL4_MERGED_reduce <- reduce(MLL4_MERGED, drop.empty.ranges=FALSE, min.gapwidth=1L,
                                 with.revmap=FALSE,
                                 with.inframe.attrib=FALSE, ignore.strand=FALSE)


ol <- findOverlapsOfPeaks(Control_Menin_reduce, Control_Set1a_reduce, MLL4_MERGED_reduce)
makeVennDiagram(ol, NameOfPeaks=c("Control_Menin", "Control_Set1a",
                                  "MLL4_MERGED"),
                fill=c("#CC79A7", "#56B4E9", "#F0E442"),
                col=c("#D55E00", "#0072B2", "#E69F00"), 
                cat.col=c("#D55E00", "#0072B2", "#E69F00"))
```
When there are only 2 sets, `makeVennDiagram` show the circle size in the same proportion as the number of peaks.
![image](https://user-images.githubusercontent.com/33963919/216095153-88436d35-2cfe-4908-9c60-363a6b7e84f5.png)
But when there are 3 sets or more, `makeVennDiagram` show the circle size all the same.
![image](https://user-images.githubusercontent.com/33963919/216095605-f342de89-bd20-4764-9ff4-eb0b4eb21163.png)

How to set the circle size in the same proportion as the number of peaks when there are more than 2 sets using `makeVennDiagram`?
Thanks

**Comment by hukai916** [comment]
I bet it rather challenging to make proportional Venn Diagrams with more than 2 sets. It is mathematically not possible in my mind.

**Comment by danli349** [comment]
@hukai916 How about if we can use ovals instead of only round circles? Thanks

**Comment by hukai916** [comment]
> @hukai916 How about if we can use ovals instead of only round circles? Thanks

It is possible with ovals @danli349, this R package can do that: https://cran.r-project.org/web/packages/eulerr/vignettes/introduction.html

Just follow @jianhong's documentation and draw with your favorable third-party plotting tools.

**Comment by danli349** [comment]
@hukai916 @jianhong That is awesome. Thanks a lot.
