### ISSUE TITLE
Regarding oligoSummary()

### ISSUE THREAD

**Issue by hukai916** [jianhong/ChIPpeakAnno#36]
Hi Jianhong,

Is there a reference for : https://github.com/jianhong/ChIPpeakAnno/blob/df99dece50f4be6f13c317b222484d5116483f30/R/oligoSummary.R#L214

Thanks,

**Comment by jianhong** [comment]
I think this is just the calculation of variance based on the binomial distribution p*(1-p)/n. Correct me if I'm wrong.

Jianhong.

From: hukai916 ***@***.***>
Date: Monday, November 20, 2023 at 4:22 PM
To: jianhong/ChIPpeakAnno ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jianhong/ChIPpeakAnno] Regarding oligoSummary() (Issue #36)

Hi Jianhong,

Is there a reference for : https://github.com/jianhong/ChIPpeakAnno/blob/df99dece50f4be6f13c317b222484d5116483f30/R/oligoSummary.R#L214

Thanks,
