### ISSUE TITLE
Bug in makeVennDiagram.R

### ISSUE THREAD

**Issue by adamd3** [jianhong/ChIPpeakAnno#6]
On line 373, the argument `otherCount` is passed to the plotting function, but the correct argument is `otherCounts` (see line 113).

This causes a "0" to be plotted in the Venn Diagram when `otherCount` is 0.

**Comment by jianhong** [comment]
It will not affect the results. see http://adv-r.had.co.nz/Functions.html#function-arguments. 
Anyway I will fix the parameter name to full parameter name.
